services:
  - type: web
    name: osi-app
    env: node
    plan: starter
    buildCommand: |
      mkdir -p /data && 
      chmod 777 /data && 
      npm ci --include=dev && 
      NODE_ENV=production npm run build
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        value: /data/db.sqlite
    healthCheckPath: /api/health
    autoDeploy: true
    disk:
      - name: uploads
        mountPath: /uploads
        sizeGB: 1
      - name: data
        mountPath: /data
        sizeGB: 1
    scaling:
      minInstances: 1
      maxInstances: 3
      targetMemoryPercent: 80
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=31536000 